service: jamesworden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

useDotenv: true

functions:
    api:
        handler: .build/index.handler
        package:
            include:
                - 'build/**/*'
                - '!build/**/*.map'
                - '!node_modules/aws-sdk/**/*'
        events:
            - http:
                  path: /
                  method: get
                  cors: true
            - http:
                  path: /docs
                  method: get
                  cors: true
            - http:
                  path: /schedule
                  method: get
                  cors: true
            - http:
                  path: /api/image
                  method: get
                  cors: true
            - http:
                  path: /api/route
                  method: get
                  cors: true
            - http:
                  path: /api/report
                  method: get
                  cors: true

plugins:
    - serverless-dotenv-plugin
