service: james-worden-research-api

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221

stage: dev
region: us-east-1

functions:
    app-api:
        handler: handler.handler
        events:
            - http:
                  path: /
                  method: get
                  cors: true
            - http:
                  path: /{proxy+}
                  method: any
                  cors: true
