service: jamesworden-research

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

useDotenv: true

functions:
  api:
    handler: .build/handler.handler
    package:
      include:
        - 'build/**/*'
        - '!build/**/*.map'
        - '!node_modules/aws-sdk/**/*'
        - '!node_modules/cypress/**/*'
    events:
      - http:
          path: /
          method: get
          cors: false
      - http:
          path: /docs
          method: get
          cors: false
      - http:
          path: /map
          method: get
          cors: false
      - http:
          path: /api/v1/route
          method: get
          cors: false
      - http:
          path: /api/v1/report
          method: get
          cors: false
      - http:
          path: /api/v1/point
          method: get
          cors: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
