service: james-worden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    # Enviornment variables are managed through AWS
    enviornment:
        GOOGLE_MAPS_API_KEY: ${ssm:/GOOGLE_MAPS_API_KEY} #-GOOGLE_MAPS_API_KEY

stage: dev
region: us-east-1

functions:
    api:
        handler: handler.handler
        events:
            # Default route
            # - http:
            #       path: /
            #       method: get
            #       cors: true
            - http:
                  path: /{proxy+}
                  method: get
                  cors: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
