service: james-worden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221

useDotenv: true

functions:
    api:
        handler: src/index.handler
        events:
            - http:
                  path: /
                  method: get
                  cors: true
            - http:
                  path: /api/route
                  method: get
                  cors: true
            - http:
                  path: /api/report
                  method: get
                  cors: true

plugins:
    - serverless-dotenv-plugin
    - serverless-plugin-typescript
