service: james-worden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    # Enviornment variables are managed through AWS
    # Check './src/enviornment.js' for more details

stage: dev
region: us-east-1

iamRoleStatements:
    - Effect: "Allow"
        Action:
            - "secretsmanager:GetSecretValue"
        Resource:
            "arn:aws:secretsmanager:us-east-1:390078892229:secret:GOOGLE_MAPS_API_KEY-Hga0iu"

functions:
    api:
        handler: handler.handler
        events:
            # Default route
            # - http:
            #       path: /
            #       method: get
            #       cors: true
            - http:
                  path: /{proxy+}
                  method: get
                  cors: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
