service: james-worden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    # Enviornment variables are managed through GitHub Secrets
    # Add new ones by editing the .github/workflows/main.yml

stage: dev
region: us-east-1

functions:
    html:
        handler: handler.html
        events:
            - http:
                  path: /
                  method: get
    api:
        handler: handler.handler
        events:
            - http:
                  path: /route
                  method: get
                  cors: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-aws-static-file-handler
