service: james-worden-research

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    enviornment:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

stage: dev
region: us-east-1

functions:
    api:
        handler: handler.handler
        events:
            - http:
                  path: /
                  method: get
                  cors: true
            - http:
                  path: /{proxy+}
                  method: any
                  cors: true
    timeout: 60 # Seconds
    memorySize: 256 # Mb
