export enum Status {
	OK = 'OK',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
	NOT_INITALIZED = 'NOT_INITALIZED',
	EXCEEDED_MAXIMUM_DISTANCE = 'EXCEEDED_MAXIMUM_DISTANCE',
	NO_TEXT_DATA = 'NO_TEXT_DATA',
	DIFFERENT_ROUTES = 'DIFFERENT_ROUTES',
}
