import * as React from 'react'

import {A, Container, Header, Hr, Map, Section} from '../components'

import {Layout} from '../Layout'
import {Route} from '../../model/route/route'

interface Home {
  route: Route
}

const horizontalFlex: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'row',
  justifyContent: 'space-between'
}

const verticalFlex: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column'
}

export default class extends React.Component<Home> {
  render() {
    return (
      <Layout title="Environmental Text Extraction">
        <Container>
          <Header title="Environmental Text Extraction">
            <p>
              Text can be extracted from pictures of outside world for a variety
              of purposes. Experiement with the <A href="/map">map</A>
              {', read the '}
              <A href="/docs">documentation</A>
              {', or view the '}
              <A href="https://github.com/jamesworden/jamesworden-research">
                source code
              </A>{' '}
              to see how this webiste and environmental text extraction works
              under the hood.
            </p>
          </Header>
          <Section paddingTop={true}>
            <p>
              Here's some sample data generated by the Route API on the map
              below. Go ahead and click the markers to reveal each point's data.
              You can also view the Point data within Google Street View to see
              where text was extracted from.
            </p>
            <div style={verticalFlex}>
              <div style={horizontalFlex}>
                <span>
                  <strong>Origin:</strong> {this.props.route.origin}
                </span>
                <span>
                  <strong>Destination:</strong> {this.props.route.destination}
                </span>
              </div>
              <div style={horizontalFlex}>
                <span>
                  <strong>Distance:</strong>{' '}
                  {`${this.props.route.distance} meters`}
                </span>
                <span>
                  <strong>Increment distance:</strong>{' '}
                  {`${this.props.route.increment} meters`}
                </span>
              </div>
            </div>
          </Section>
          <Section paddingTop={true}>
            <Map route={this.props.route} zoom={17} />
          </Section>
        </Container>
      </Layout>
    )
  }
}
