export const LIGHT_BLUE: string = '#5494F5'
export const DARK_BLUE: string = '#4056DE'
export const PURPLE: string = '#6049FA'
export const BLUE_GREEN: string = '#40A9DE'
export const TEAL: string = '#49EDFA'
export const BLACK: string = '#000'
export const LIGHT_GREY: string = 'lightgrey'
export const WHITE: string = '#fff'
