name: Deploy master branch

on:
    push:
        branches:
            - master

    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
            tags:
                description: 'Test'

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Begin deployment...
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            # - run: npm run coverage || true

            - name: Inject enviornment variables with GitHub secrets
              run: |
                  touch .env
                  echo "GOOGLE_MAPS_FRONTEND_KEY=${{ secrets.GOOGLE_MAPS_FRONTEND_KEY }}" >> .env
                  echo "GOOGLE_MAPS_BACKEND_KEY=${{ secrets.GOOGLE_MAPS_BACKEND_KEY }}" >> .env
                  echo "RESEARCH_API_KEY=${{ secrets.RESEARCH_API_KEY }}" >> .env
                  echo "GOOGLE_APPLICATION_CREDENTIALS="./GoogleServiceCredentials.json"" >> .env

                  touch GoogleServiceCredentials.json
                  echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> GoogleServiceCredentials.json

            - name: Zip Node Modules
              run: npm install && zip -qq -r -j ./node_modules.zip ./node_modules/*

            - name: Deploy node modules to Lambda Layer
            - name: AWS Lambda Layer Publish
              uses: taotao2345/aws-lambda-publishlayer@v1.0.0
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              with:
                  layer_name: jamesworden-research-dependencies
                  zip_file: node_modules.zip

            - name: Compile typescript and zip api js files
              run: npm build && zip -qq -r -j ./api.zip ./dist/*

            - name: Deploy API to AWS Lambda
              uses: appleboy/lambda-action@master
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  function_name: jamesworden-research
                  zip_file: api.zip
    test:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Run tests
              run: npm test
