name: Deploy master branch

on:
    push:
        branches:
            - master

    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
            tags:
                description: 'Test'

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Begin deployment...
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            - run: npm run coverage || true

            - name: Inject enviornment variables with GitHub secrets
              run: |
                  touch .env
                  echo "GOOGLE_MAPS_FRONTEND_KEY=${{ secrets.GOOGLE_MAPS_FRONTEND_KEY }}" >> .env
                  echo "GOOGLE_MAPS_BACKEND_KEY=${{ secrets.GOOGLE_MAPS_BACKEND_KEY }}" >> .env
                  echo "RESEARCH_API_KEY=${{ secrets.RESEARCH_API_KEY }}" >> .env
                  echo "GOOGLE_APPLICATION_CREDENTIALS="./GoogleServiceCredentials.json"" >> .env

                  touch GoogleServiceCredentials.json
                  echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> GoogleServiceCredentials.json

            - name: Install dependencies, Build application and Zip dist folder contents
              run: npm install && npm run build && zip -qq -r -j ./bundle.zip ./dist/*
            - name: deploy zip to aws lambda
              uses: appleboy/lambda-action@master
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  function_name: jamesworden-research
                  zip_file: bundle.zip
    test:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Run tests
              run: npm test
